### ISSUE TITLE
报错OSError: [WinError 123] 文件名、目录名或卷标语法不正确。

### ISSUE THREAD

**Issue by czgaotian** [hey-bruce/algorithms_and_oj#1]
```
Traceback (most recent call last):
  File "readme.py", line 253, in <module>
    main()
  File "readme.py", line 249, in main
    table.update_table('leetcode')
  File "readme.py", line 113, in update_table
    self.__create_folder(oj)
  File "readme.py", line 104, in __create_folder
    os.mkdir(question_folder_name)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:/Users/admin/Desktop/leedcode/leetcode-algorithms/785. Is Graph Bipartite?'
```
python 我不是很熟，这里这么报错怎么处理呢

然后，我上面的设置是这样的
```
    local_path = 'C:/Users/admin/Desktop/leedcode'
    github_leetcode_url = 'https://github.com/czgaotian/leetcode/blob/master/leetcode-algorithms/'
    github_pat_url = 'https://github.com/czgaotian/leetcode/blob/master/pat-algorithms/'
    leetcode_url = 'https://leetcode.com/problems/'
```

另外，`leetcode-algorithms`这个文件夹可以改名吗

**Comment by bbruceyuan** [comment]
1. 因为我是再linux下面设置的路径，你是在windows下面，所以当windows创建的文件夹名字后面不能有 “？”。这里我马上修复一下，按照道理只要去掉问号就能成功。你可以把我待会重新上传的`readme.py`文件复制更新一下，应该就好了。
2.  这个`leetcode-algorithms`文件夹是可以随便更改的，只要你同时把`github_leetcode_url`中master后面的部分也修改了就行了。比如：你想改成`algorithms`就需要把`github_leetcode_url`改成`github_leetcode_url = 'https://github.com/czgaotian/leetcode/blob/master/algorithms/'`,此外，还需要更改update函数中`oj_algorithms = Config.local_path + '/' + oj + '-algorithms'`中改成`oj_algorithms = Config.local_path + '/' + 'algorithms'`。这个也许我后期需要修改一下。你先暂时这么用着吗？

**Comment by bbruceyuan** [comment]
你好！

现在我修改完了。第一个问题已经修复，应该会没问题了。

第二个问题，我也以及自己修改了。所以你只需要修改main函数中`table.update_table('leetcode-algorithms')`中的输入参数就行了。把leetcode-algorithms改成你想要的名字就行了。

如果还有啥问题，欢迎继续留言讨论，谢谢！

**Comment by czgaotian** [comment]
ok，已经弄好了 ，感谢解答。
原来是 `785. Is Graph Bipartite?` 这个问题自带问号

**Comment by czgaotian** [comment]
还有一个问题，我生成的链接路径还是不对
`|Easy|[JavaScript](https://github.com/czgaotian/leedcode/blob/master/leetcode-algorithms/001.%20Two%20Su\Two_Su.js)|To Do|To Do|`
这个应该还是win和linux路径的问题吧，应该怎么解决呢

找了点资料,这样解决会有什么问题吗
```
elif item.endswith('.js'):
                            complete_info.solved['javascript'] += 1
                            folder_url = folder.replace(' ', "%20")
                            folder_url = os.path.join(folder_url, item)
                            folder_url = os.path.join(Config.github_leetcode_url, folder_url)
                            # 解决路径'\'不对的问题
                            folder_url = folder_url.replace('\\','/')
```

**Comment by bbruceyuan** [comment]
我看你的解决方法应该没啥问题。不过你需要在每一次判断endswith()后面都加上`folder_url = folder_url.replace('\\','/')`。不然你只解决了js文件的路径问题。你可以自己多尝试一下

**Comment by czgaotian** [comment]
好的，该学python了我
